# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SHOC_PUBLIC_REGISTRY: ghcr.io
  SHOC_PUBLIC_REPOSITORY: ${{ github.repository }}/public
  SHOC_PUBLIC_VERSION: ${{ github.sha }}

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish Builder
      run: dotnet publish Shoc.Builder/Shoc.Builder.csproj -c Release -o Shoc.Builder/bin/Release/net6.0/publish/
    
    - name: Build all images
      run: docker-compose build shoc-builder
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.SHOC_PUBLIC_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.SHOC_GHCR_TOKEN }}

    - name: Push all images
      run: docker-compose push shoc-builder
      
